USE card;
CREATE TABLE card_issues
(
    id         BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '발급 이력 고유 ID',
    user_id    BIGINT      NOT NULL COMMENT '사용자 식별자',
    status     VARCHAR(30) NOT NULL COMMENT '발급 상태 (PENDING, SUCCESS, FAIL)',
    created_at DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    updated_at DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시'
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci COMMENT ='PLCC 카드 발급 이력';
